### ISSUE TITLE
Store a list of current repos which use the JSON Schema topic and when they were created

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/ecosystem#4]
This work has been started but still has some work to be done.
See https://github.com/json-schema-org/ecosystem/tree/main/projects/initial-data for work so far.

Currently, it checks the earliest record in the way back machine (WBM) for the repo to see if it has the JSON Schema topic. I don't think it should do that any more. It seemed like a good idea at the time.

The code currently collects all the Github topics the repo reports, which I think we can use to do some analysis. Might as well collect that data while it's there!

Here's the work that needs to be done on this:

- [ ] No longer check the way back machine for earliest use of the `json-schema` github topic and no longer record the data related to the way back machine
- [ ] Get the date of the first commit for a repo and store that in the CSV as a timestamp
- [ ] Confirm the initial data script can be run fully and include the created CSV as a commit
- [ ] Catch any potential error and log into a file, without causing the script to crash, and allowing it to continue if appropriate.

Stretch objectives:

- [ ] Write tests which [mock the Github API calls](https://mswjs.io) and [mock the file writing](https://medium.com/nerd-for-tech/testing-in-node-js-easy-way-to-mock-filesystem-883b9f822ea4), and check it has the correct content for the API data mocked.

The WBM has an API limit of 500 calls per hour, while Githubs limit for the API endpoint used is 5,000 per hour (when using a Github Personal Access Token (PAT)).

**Comment by ayushtiwari110** [comment]
@Relequestual Maybe I can take this one? I'm new to the library used in the mentioned project, but eager to learn and work on this...

**Comment by sncshr** [comment]
@Relequestual Let me know this task is still unassigned. I will be happy to take it!

**Comment by satyam-x10** [comment]
@Relequestual This looks interesting to work on.. Can i please work on this ?Thanks

**Comment by wcj617** [comment]
@Relequestual 
I will start working on this

**Comment by satyam-x10** [comment]
@benjagm is this open to work on ?

**Comment by benjagm** [comment]
@wcj617 please go ahead with this issue. Thanks!

**Comment by wcj617** [comment]
This is my second qualification task work!
[second qualification task.pdf](https://github.com/json-schema-org/ecosystem/files/14813528/second.qualification.task.pdf)
